name: Build NDS ROM

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Example Game
        run: |
          cd templates/application
          make

      - name: Upload NDS ROM
        uses: actions/upload-artifact@v4
        with:
          name: gioco-anniversario
          path: templates/application/*.nds
